function [h] = plotarrow(X,U,str)

% plot arrow U from origin X, control string str

if nargin < 3
    h = quiver3([X(1) X(1)],[X(2) X(2)],[X(3) X(3)],...
        [U(1) U(1)],...
        [U(2) U(2)],...
        [U(3) U(3)],0.5,'LineWidth',2);
else
    h = quiver3([X(1) X(1)],[X(2) X(2)],[X(3) X(3)],...
        [U(1) U(1)],...
        [U(2) U(2)],...
        [U(3) U(3)],0.5,str,'LineWidth',2);
end